# Change these first
owner: RewstApp # Your GitHub organization or username, where this repository lives
repo: status.rewst.io # The name of this repository

sites:
  - name: Rewst App
    url: $REWST_APP
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Rewst API
    url: $REWST_API
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Rewst Engine
    url: $REWST_ENGINE
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Rewst CDN
    url: $REWST_CDN
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Rewst Workflow
    url: $REWST_WORKFLOW
    expectedStatusCodes:
      - 200
      - 201
      - 404


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.rewst.io
  # baseUrl: /your-repo-name
  name: ""
  logoUrl: https://cdn.rewst.io/logos/horizontal-logos/png/rewst-logo-horizontal-white.png
  themeUrl: https://status.rewst.io/rewst.css
  favicon: https://status.rewst.io/favicon.png
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    # - title: GitHub
    #   href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  footer: ""